modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="cellcraft"
version="${version}"
displayName="CellCraft"
description="A Minecraft mod for cellular automata and crafting"
authors="yeocci"
logoFile="logo.png"

[[dependencies.cellcraft]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cellcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
