org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Properties
mod_version=1.0.0
mod_id=cellcraft
mod_name=CellCraft
mod_author=yeocci
mod_description=A Minecraft mod for cellular automata and crafting

# Minecraft Properties
minecraft_version=1.20.1
enabled_platforms=fabric,forge

# Fabric Properties
fabric_loader_version=0.15.11
fabric_api_version=0.92.2+1.20.1

# Forge Properties
forge_version=47.3.0

# Architectury
architectury_version=9.2.14

# Mappings
parchment_version=2023.09.03
yarn_mappings=1.20.1+build.10
